### ISSUE TITLE
Add twine setup for PyPI

### ISSUE THREAD

**Issue by marshallmcdonnell** [ChalkLab/SciDataLib#27]
From discussions in meeting on 04/13/2021, came up with following bullet items:

- [x] Create the PyPi account that will host the SciDataLib package (@JohnsonDylan will lead this)
- [x] Figure out the description for the package on PyPi and update the `long_description` in `setup.py` (@stuchalk will lead this). Currently, we are using the [entire README](https://github.com/ChalkLab/SciDataLib/blob/master/setup.py#L4-L5) in the [`setup.py` lines](https://github.com/ChalkLab/SciDataLib/blob/master/setup.py#L13) , which is probably a bit too verbose)
- [x] Need to create an API token using the PyPi account. This is under "Account Settings" -> "API Tokens" to create the token. We only need scope for the SciDataLib project.
- [x] Once we have that API token, we need to place it in the GitHub Secrets (in GitHub under "Settings" -> "Secrets") Then we create a "Repository Secret" with the token.
- [x] Use the name of that secret in the GitHub Actions yaml to add a deploy stage to PyPi following the below example:
```
   - name: Build Python package and Upload to PyPi
        shell: bash -l {0}
        if: startsWith( github.ref, 'refs/tags/v') && matrix.python-version == env.PYTHON_MAIN_VERSION
        env: 
            PYPI_TOKEN_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          pip install wheel twine
          python setup.py sdist bdist_wheel
          twine upload --username "__token__" --password $PYPI_TOKEN_PASSWORD dist/*
```

**Comment by stuchalk** [comment]
Well I decided to go with the verbose description after all.  We can fix this in a future release :)
