### ISSUE TITLE
Add the "type" and "property" to the SciData class

### ISSUE THREAD

**Issue by marshallmcdonnell** [ChalkLab/SciDataLib#53]
In the SciData framework, in the `@graph` section, there is the the `scidata.type` (usually "property value") and `scidata.property`:
https://github.com/stuchalk/scidata/blob/master/examples/sections/framework_plus.jsonld#L32-L33

Would like to include a method that allows for including these values in the SciData object.

**Comment by stuchalk** [comment]
I have decided to create a discussion topic to address this suggestion...

**Comment by marshallmcdonnell** [comment]
@stuchalk sounds good, thanks!
Should I hold off on trying to implement this?
I am already working on it now (finished with "type", working on "properties") but can pause, especially if we don't want to add these.

**Comment by stuchalk** [comment]
#54

**Comment by marshallmcdonnell** [comment]
@stuchalk based on #54 I am fine to close this issue since will go with the `ids` instead.
Sound good?

**Comment by stuchalk** [comment]
As I said in the discussion, if you feel you don't need these metadata elements and can use the 'ids' right now then close this issue.  We can always reopen it later if needed...

**Comment by marshallmcdonnell** [comment]
Sounds good and I think I can right now :+1:
