### ISSUE TITLE
Iterate function (__iterate_function) does not properly enumerate/increment beyond one level of nesting

### ISSUE THREAD

**Issue by JohnsonDylan** [ChalkLab/SciDataLib#63]
Left shows current output, right shows expected output

<img width="1680" alt="Screen Shot 2021-06-09 at 10 22 46 AM" src="https://user-images.githubusercontent.com/50339515/121405087-9f19a700-c92a-11eb-9234-3b4e4fad8b79.png">

**Comment by marshallmcdonnell** [comment]
@JohnsonDylan 
Apologies, I think https://github.com/ChalkLab/SciDataLib/pull/64 should have closed this issue and I forgot to "link" them (via "closes #<issue number>" in the PR.

Just checking, this is fixed, correct?

**Comment by JohnsonDylan** [comment]
That’s correct. This issue appears to be fixed from my tests. Thanks

**Comment by marshallmcdonnell** [comment]
closed via #64

**Comment by JohnsonDylan** [comment]
<img width="753" alt="Screen Shot 2021-07-23 at 5 25 36 PM" src="https://user-images.githubusercontent.com/50339515/126998867-c0549976-5752-4e37-917f-e779b589a6e4.png">

Issue shown in initial image is fixed but another problem was noticed. Modified the example.py file to emphasize the issue shown in the attached image.

**Comment by marshallmcdonnell** [comment]
Thanks for re-opening and the example, @JohnsonDylan!
My thought on a "first step" is let's get this into a test that currently fails for us.
After that, can use it to start figuring out what is going on and debug.

To help on that "first step", do you mind to drop the above as "text" (instead of image type) for output and also the input you gave so we can create that input -> test -> target output?

**Comment by JohnsonDylan** [comment]
`[
    {
        "@id": "compound",
        "name": "cyanide ion",
        "inchi": "InChI=1S/CN/c1-2/q-1",
        "chebi": "obo:CHEBI_17514"
    },
    {
        "@id": "compound",
        "name": "phenolphthlin",
        "inchi": "InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",
        "chebi": "obo:CHEBI_34915"
    },
    {
        "@id": "compound",
        "name": "copper(II) ion",
        "inchi": "InChI=1S/Cu/q+2",
        "chebi": "obo:CHEBI_29036"
    },
    {
        "@id": "compound",
        "name": "tetraborate ion",
        "inchi": "InChI=1S/B4H4O9/c5-1-9-3(7)11-2(6)12-4(8,10-1)13-3/h5-8H/q-2",
        "chebi": "obo:CHEBI_38889"
    },
    {
        "@id": "compound",
        "name": "ethanol",
        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
        "chebi": "obo:CHEBI_16236"
    },
    {
        "@id": "compound",
        "name": "water",
        "inchi": "InChI=1S/H2O/h1H2",
        "chebi": "obo:CHEBI_15377"
    },
    {
        "@id": "substance",
        "title": "3 ppm cyanide standard solution",
        "aggregation": "sub:aq",
        "mixtype": "sub:homogeneousSolution",
        "phase": "sub:liquid",
        "constituents": [
            {
                "@id": "constituent",
                "source": "compound/1/",
                "role": "chm:analyte",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/2/",
                "role": "chm:reagent",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/3/",
                "role": "chm:reagent"
            },
            {
                "@id": "constituent",
                "source": "compound/4/",
                "role": "chm:buffer"
            },
            {
                "@id": "constituent",
                "source": "compound/5/",
                "role": "chm:solvent"
            },
            {
                "@id": "constituent",
                "source": "compound/6/",
                "role": "chm:solvent"
            }
        ],
        "properties": [
            {
                "@id": "property",
                "quantity": "volume",
                "property": "Volume of solution",
                "value": {
                    "@id": "value",
                    "number": 100.0,
                    "unitref": "qudt:MilliL"
                }
            }
        ]
    },
    {
        "@id": "condition",
        "source": "measurement/1/",
        "scope": "substance/1/",
        "quantity": "temperature",
        "property": "Ambient temperature",
        "propertyref": "gb:T06321",
        "value": {
            "@id": "value",
            "number": 22.8,
            "unitref": "qudt:DEG_C"
        }
    }
]
`

**Comment by JohnsonDylan** [comment]
[
    {
        "@id": "compound",
        "name": "cyanide ion",
        "inchi": "InChI=1S/CN/c1-2/q-1",
        "chebi": "obo:CHEBI_17514"
    },
    {
        "@id": "compound",
        "name": "phenolphthlin",
        "inchi": "InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",
        "chebi": "obo:CHEBI_34915"
    },
    {
        "@id": "compound",
        "name": "copper(II) ion",
        "inchi": "InChI=1S/Cu/q+2",
        "chebi": "obo:CHEBI_29036"
    },
    {
        "@id": "compound",
        "name": "tetraborate ion",
        "inchi": "InChI=1S/B4H4O9/c5-1-9-3(7)11-2(6)12-4(8,10-1)13-3/h5-8H/q-2",
        "chebi": "obo:CHEBI_38889"
    },
    {
        "@id": "compound",
        "name": "ethanol",
        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
        "chebi": "obo:CHEBI_16236"
    },
    {
        "@id": "compound",
        "name": "water",
        "inchi": "InChI=1S/H2O/h1H2",
        "chebi": "obo:CHEBI_15377"
    },
    {
        "@id": "substance",
        "title": "3 ppm cyanide standard solution",
        "aggregation": "sub:aq",
        "mixtype": "sub:homogeneousSolution",
        "phase": "sub:liquid",
        "constituents": [
            {
                "@id": "constituent",
                "source": "compound/1/",
                "role": "chm:analyte",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/2/",
                "role": "chm:reagent",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/3/",
                "role": "chm:reagent"
            },
            {
                "@id": "constituent",
                "source": "compound/4/",
                "role": "chm:buffer"
            },
            {
                "@id": "constituent",
                "source": "compound/5/",
                "role": "chm:solvent"
            },
            {
                "@id": "constituent",
                "source": "compound/6/",
                "role": "chm:solvent"
            }
        ],
        "properties": [
            {
                "@id": "property",
                "quantity": "volume",
                "property": "Volume of solution",
                "value": {
                    "@id": "value",
                    "number": 100.0,
                    "unitref": "qudt:MilliL"
                }
            }
        ]
    },
    {
        "@id": "condition",
        "source": "measurement/1/",
        "scope": "substance/1/",
        "quantity": "temperature",
        "property": "Ambient temperature",
        "propertyref": "gb:T06321",
        "value": {
            "@id": "value",
            "number": 22.8,
            "unitref": "qudt:DEG_C"
        }
    }
]

**Comment by JohnsonDylan** [comment]
``[
    {
        "@id": "compound",
        "name": "cyanide ion",
        "inchi": "InChI=1S/CN/c1-2/q-1",
        "chebi": "obo:CHEBI_17514"
    },
    {
        "@id": "compound",
        "name": "phenolphthlin",
        "inchi": "InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",
        "chebi": "obo:CHEBI_34915"
    },
    {
        "@id": "compound",
        "name": "copper(II) ion",
        "inchi": "InChI=1S/Cu/q+2",
        "chebi": "obo:CHEBI_29036"
    },
    {
        "@id": "compound",
        "name": "tetraborate ion",
        "inchi": "InChI=1S/B4H4O9/c5-1-9-3(7)11-2(6)12-4(8,10-1)13-3/h5-8H/q-2",
        "chebi": "obo:CHEBI_38889"
    },
    {
        "@id": "compound",
        "name": "ethanol",
        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
        "chebi": "obo:CHEBI_16236"
    },
    {
        "@id": "compound",
        "name": "water",
        "inchi": "InChI=1S/H2O/h1H2",
        "chebi": "obo:CHEBI_15377"
    },
    {
        "@id": "substance",
        "title": "3 ppm cyanide standard solution",
        "aggregation": "sub:aq",
        "mixtype": "sub:homogeneousSolution",
        "phase": "sub:liquid",
        "constituents": [
            {
                "@id": "constituent",
                "source": "compound/1/",
                "role": "chm:analyte",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/2/",
                "role": "chm:reagent",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/3/",
                "role": "chm:reagent"
            },
            {
                "@id": "constituent",
                "source": "compound/4/",
                "role": "chm:buffer"
            },
            {
                "@id": "constituent",
                "source": "compound/5/",
                "role": "chm:solvent"
            },
            {
                "@id": "constituent",
                "source": "compound/6/",
                "role": "chm:solvent"
            }
        ],
        "properties": [
            {
                "@id": "property",
                "quantity": "volume",
                "property": "Volume of solution",
                "value": {
                    "@id": "value",
                    "number": 100.0,
                    "unitref": "qudt:MilliL"
                }
            }
        ]
    },
    {
        "@id": "condition",
        "source": "measurement/1/",
        "scope": "substance/1/",
        "quantity": "temperature",
        "property": "Ambient temperature",
        "propertyref": "gb:T06321",
        "value": {
            "@id": "value",
            "number": 22.8,
            "unitref": "qudt:DEG_C"
        }
    }
]

**Comment by JohnsonDylan** [comment]
Input:

`[
    {
        "@id": "compound",
        "name": "cyanide ion",
        "inchi": "InChI=1S/CN/c1-2/q-1",
        "chebi": "obo:CHEBI_17514"
    },
    {
        "@id": "compound",
        "name": "phenolphthlin",
        "inchi": "InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",
        "chebi": "obo:CHEBI_34915"
    },
    {
        "@id": "compound",
        "name": "copper(II) ion",
        "inchi": "InChI=1S/Cu/q+2",
        "chebi": "obo:CHEBI_29036"
    },
    {
        "@id": "compound",
        "name": "tetraborate ion",
        "inchi": "InChI=1S/B4H4O9/c5-1-9-3(7)11-2(6)12-4(8,10-1)13-3/h5-8H/q-2",
        "chebi": "obo:CHEBI_38889"
    },
    {
        "@id": "compound",
        "name": "ethanol",
        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
        "chebi": "obo:CHEBI_16236"
    },
    {
        "@id": "compound",
        "name": "water",
        "inchi": "InChI=1S/H2O/h1H2",
        "chebi": "obo:CHEBI_15377"
    },
    {
        "@id": "substance",
        "title": "3 ppm cyanide standard solution",
        "aggregation": "sub:aq",
        "mixtype": "sub:homogeneousSolution",
        "phase": "sub:liquid",
        "constituents": [
            {
                "@id": "constituent",
                "source": "compound/1/",
                "role": "chm:analyte",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/2/",
                "role": "chm:reagent",
                "properties": [
                    {
                        "@id": "property",
                        "quantity": "mass of substance per volume",
                        "property": "Concentration (w/v)",
                        "value": {
                            "@id": "value",
                            "number": 2.99,
                            "unitref": "qudt:PPM"
                        }
                    },
                    {
                        "@id": "property",
                        "quantity": "volume",
                        "property": "Volume of solution",
                        "value": {
                            "@id": "value",
                            "number": 100.0,
                            "unitref": "qudt:MilliL"
                        }
                    }
                ]
            },
            {
                "@id": "constituent",
                "source": "compound/3/",
                "role": "chm:reagent"
            },
            {
                "@id": "constituent",
                "source": "compound/4/",
                "role": "chm:buffer"
            },
            {
                "@id": "constituent",
                "source": "compound/5/",
                "role": "chm:solvent"
            },
            {
                "@id": "constituent",
                "source": "compound/6/",
                "role": "chm:solvent"
            }
        ],
        "properties": [
            {
                "@id": "property",
                "quantity": "volume",
                "property": "Volume of solution",
                "value": {
                    "@id": "value",
                    "number": 100.0,
                    "unitref": "qudt:MilliL"
                }
            }
        ]
    },
    {
        "@id": "condition",
        "source": "measurement/1/",
        "scope": "substance/1/",
        "quantity": "temperature",
        "property": "Ambient temperature",
        "propertyref": "gb:T06321",
        "value": {
            "@id": "value",
            "number": 22.8,
            "unitref": "qudt:DEG_C"
        }
    }
]
`

Output:

`{
                "@id": "system/",
                "@type": "sdo:system",
                "facets": [
                    {
                        "@id": "compound/1/",
                        "@type": "sdo:compound",
                        "name": "cyanide ion",
                        "inchi": "InChI=1S/CN/c1-2/q-1",
                        "chebi": "obo:CHEBI_17514"
                    },
                    {
                        "@id": "compound/2/",
                        "@type": "sdo:compound",
                        "name": "phenolphthlin",
                        "inchi": "InChI=1S/C6H6O/c7-6-4-2-1-3-5-6/h1-5,7H",
                        "chebi": "obo:CHEBI_34915"
                    },
                    {
                        "@id": "compound/3/",
                        "@type": "sdo:compound",
                        "name": "copper(II) ion",
                        "inchi": "InChI=1S/Cu/q+2",
                        "chebi": "obo:CHEBI_29036"
                    },
                    {
                        "@id": "compound/4/",
                        "@type": "sdo:compound",
                        "name": "tetraborate ion",
                        "inchi": "InChI=1S/B4H4O9/c5-1-9-3(7)11-2(6)12-4(8,10-1)13-3/h5-8H/q-2",
                        "chebi": "obo:CHEBI_38889"
                    },
                    {
                        "@id": "compound/5/",
                        "@type": "sdo:compound",
                        "name": "ethanol",
                        "inchi": "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3",
                        "chebi": "obo:CHEBI_16236"
                    },
                    {
                        "@id": "compound/6/",
                        "@type": "sdo:compound",
                        "name": "water",
                        "inchi": "InChI=1S/H2O/h1H2",
                        "chebi": "obo:CHEBI_15377"
                    },
                    {
                        "@id": "substance/1/",
                        "@type": "sdo:substance",
                        "title": "3 ppm cyanide standard solution",
                        "aggregation": "sub:aq",
                        "mixtype": "sub:homogeneousSolution",
                        "phase": "sub:liquid",
                        "constituents": [
                            {
                                "@id": "substance/1/constituent/1/",
                                "@type": "sdo:constituent",
                                "source": "compound/1/",
                                "role": "chm:analyte",
                                "properties": [
                                    {
                                        "@id": "substance/1/constituent/1/property/1/",
                                        "@type": "sdo:property",
                                        "quantity": "mass of substance per volume",
                                        "property": "Concentration (w/v)",
                                        "value": {
                                            "@id": "substance/1/constituent/1/property/1/value/1/",
                                            "@type": "sdo:value",
                                            "number": 2.99,
                                            "unitref": "qudt:PPM"
                                        }
                                    },
                                    {
                                        "@id": "substance/1/constituent/1/property/2/",
                                        "@type": "sdo:property",
                                        "quantity": "volume",
                                        "property": "Volume of solution",
                                        "value": {
                                            "@id": "substance/1/constituent/1/property/2/value/1/",
                                            "@type": "sdo:value",
                                            "number": 100.0,
                                            "unitref": "qudt:MilliL"
                                        }
                                    }
                                ]
                            },
                            {
                                "@id": "substance/1/constituent/2/",
                                "@type": "sdo:constituent",
                                "source": "compound/2/",
                                "role": "chm:reagent",
                                "properties": [
                                    {
                                        "@id": "substance/1/constituent/2/property/3/",
                                        "@type": "sdo:property",
                                        "quantity": "mass of substance per volume",
                                        "property": "Concentration (w/v)",
                                        "value": {
                                            "@id": "substance/1/constituent/2/property/3/value/1/",
                                            "@type": "sdo:value",
                                            "number": 2.99,
                                            "unitref": "qudt:PPM"
                                        }
                                    },
                                    {
                                        "@id": "substance/1/constituent/2/property/4/",
                                        "@type": "sdo:property",
                                        "quantity": "volume",
                                        "property": "Volume of solution",
                                        "value": {
                                            "@id": "substance/1/constituent/2/property/4/value/1/",
                                            "@type": "sdo:value",
                                            "number": 100.0,
                                            "unitref": "qudt:MilliL"
                                        }
                                    }
                                ]
                            },
                            {
                                "@id": "substance/1/constituent/3/",
                                "@type": "sdo:constituent",
                                "source": "compound/3/",
                                "role": "chm:reagent"
                            },
                            {
                                "@id": "substance/1/constituent/4/",
                                "@type": "sdo:constituent",
                                "source": "compound/4/",
                                "role": "chm:buffer"
                            },
                            {
                                "@id": "substance/1/constituent/5/",
                                "@type": "sdo:constituent",
                                "source": "compound/5/",
                                "role": "chm:solvent"
                            },
                            {
                                "@id": "substance/1/constituent/6/",
                                "@type": "sdo:constituent",
                                "source": "compound/6/",
                                "role": "chm:solvent"
                            }
                        ],
                        "properties": [
                            {
                                "@id": "substance/1/property/5/",
                                "@type": "sdo:property",
                                "quantity": "volume",
                                "property": "Volume of solution",
                                "value": {
                                    "@id": "substance/1/property/5/value/1/",
                                    "@type": "sdo:value",
                                    "number": 100.0,
                                    "unitref": "qudt:MilliL"
                                }
                            }
                        ]
                    },
                    {
                        "@id": "condition/1/",
                        "@type": "sdo:condition",
                        "source": "measurement/1/",
                        "scope": "substance/1/",
                        "quantity": "temperature",
                        "property": "Ambient temperature",
                        "propertyref": "gb:T06321",
                        "value": {
                            "@id": "condition/1/value/2/",
                            "@type": "sdo:value",
                            "number": 22.8,
                            "unitref": "qudt:DEG_C"
                        }
                    }
                ]
            }`

**Comment by marshallmcdonnell** [comment]
Perfect! Thank you!

**Comment by JohnsonDylan** [comment]
I believe I've got this worked out. Still testing but plan to commit and close shortly
